apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: koteikin/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: "32Mi"
        cpu: "256m"  
