apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec: 
  capacity:
    storage: 1Gi
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb