apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    stage: learn
spec:
  containers:
  - name: kubia-liveness
    image: luksa/kubia-unhealthy
    resources:
      limits:
        memory: "32Mi"
        cpu: "256m"
    livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15